name: Atualizar pares de moedas

on:
  schedule:
    - cron: "0 */4 * * *"  # Executa a cada hora
  workflow_dispatch:  # Permite execução manual

jobs:
  update_exchange_rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Atualizar pares de moedas no SQLite
        run: |
          python database.py  # Arquivo Python que atualiza o banco de dados SQLite

      - name: Commit e push das alterações no banco de dados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "up exchange_rates.db"
