name: Atualizar Pares de Moedas

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  Cron:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Atualizar pares de moedas
      run: |
        python app.py

    - name: Commit e push
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add database.sqlite3
        git commit -m 'up exchange_rates.db' || echo "up sem alterações para commit"
        git push
